TOP = ..
include $(TOP)/mk/boilerplate.mk

SUBDIRS = anna bspt cacheprof compress compress2 fem fluid fulsom gamteb gg \
          grep hidden hpg infer linear maillist mkhprog parser pic prolog \
          reptile rsa scs symalg veritas eff # ben-raytrace smallpt lift

#cacheprof causes very nondeterministic allocation
OTHER_SUBDIRS = cacheprof


include $(TOP)/mk/target.mk

